---
github:
  owner: getsentry
  repo: craft
changelogPolicy: simple
targets:
  - name: npm
  - name: gh-pages
  - name: github
  - name: gcs
    bucket: sentry-sdk-assets
    paths:
      - /craft/{{version}}/
      - /craft/latest/
    includeNames: /^.*craft.*$/
    maxCacheAge: 300
