minVersion: '0.13.2'
github:
  owner: getsentry
  repo: craft
changelogPolicy: simple
requireNames:
  - /^sentry-craft.*\.tgz$/
statusProvider:
  name: github
artifactProvider:
  name: github
targets:
  - name: npm
  - name: gh-pages
  - name: gcs
    includeNames: /^.*craft.*$/
    bucket: sentry-sdk-assets
    paths:
      - path: /craft/{{version}}/
        metadata:
          cacheControl: 'public, max-age=2592000'
      - path: /craft/latest/
        metadata:
          cacheControl: 'public, max-age=300'
  - name: registry
    type: app
    urlTemplate: 'https://downloads.sentry-cdn.com/craft/{{version}}/{{file}}'
    checksums:
      - algorithm: sha256
        format: hex
    config:
      canonical: 'app:craft'
  - name: github
  - name: docker
    source: us.gcr.io/sentryio/craft
    target: getsentry/craft
  - name: aws-lambda
