---
github:
  owner: getsentry
  repo: craft
changelogPolicy: simple
targets:
  - name: npm
  - name: gh-pages
  - name: github
  - name: gcs
    includeNames: /^.*craft.*$/
    bucket: sentry-sdk-assets
    paths:
      - path: /craft/{{version}}/
        maxCacheAge: 2592000
      - path: /craft/latest/
        maxCacheAge: 300
