minVersion: '0.5.0'
github:
  owner: getsentry
  repo: craft
changelogPolicy: simple
targets:
  - name: npm
  - name: gh-pages
  - name: gcs
    includeNames: /^.*craft.*$/
    bucket: sentry-sdk-assets
    paths:
      - path: /craft/{{version}}/
        metadata:
          cacheControl: 'public, max-age=2592000'
      - path: /craft/latest/
        metadata:
          cacheControl: 'public, max-age=300'
  - name: registry
    type: app
    urlTemplate: "https://downloads.sentry-cdn.com/craft/{{version}}/{{file}}"
    config:
      canonical: "app:craft"
  - name: github
