name: 'Craft'
description: 'Use getsentry/craft to publish your project'
inputs:
  action:
    description: 'The action to take. Can be either prepare or publish'
    required: true
    default: '--help'
  version:
    description: 'The version number for the new release'
    required: true
runs:
  using: 'docker'
  image: 'docker://getsentry/craft'
  args:
    - ${{ inputs.action }}
    - ${{ inputs.version }}
