steps:
  - name: 'gcr.io/kaniko-project/executor:v1.5.1'
    args:
      - '--cache=true'
      - '--use-new-run'
      - '--build-arg'
      - 'SOURCE_COMMIT=$COMMIT_SHA'
      - '--destination=us.gcr.io/$PROJECT_ID/craft:builder-$COMMIT_SHA'
      - '-f'
      - 'builder.dockerfile'
  - name: 'us.gcr.io/$PROJECT_ID/craft:builder-$COMMIT_SHA'
  - name: 'gcr.io/kaniko-project/executor:v1.5.1'
    args:
      - '--cache=true'
      - '--use-new-run'
      - '--build-arg'
      - 'SOURCE_COMMIT=$COMMIT_SHA'
      - '--destination=us.gcr.io/$PROJECT_ID/craft:$COMMIT_SHA'
    timeout: 900s
  # Smoke tests
  - name: 'us.gcr.io/$PROJECT_ID/craft:$COMMIT_SHA'
    args:
      - '--help'
    timeout: 60s
  - name: 'gcr.io/cloud-builders/docker'
    secretEnv: ['DOCKER_PASSWORD']
    entrypoint: 'bash'
    args:
      - '-e'
      - '-c'
      - |
        # Only push to Docker Hub from master
        [ "$BRANCH_NAME" != "master" ] && exit 0
        # Need to pull the image first due to Kaniko
        docker pull us.gcr.io/$PROJECT_ID/craft:$COMMIT_SHA
        echo "$$DOCKER_PASSWORD" | docker login --username=sentrybuilder --password-stdin
        docker tag us.gcr.io/$PROJECT_ID/craft:$COMMIT_SHA getsentry/craft:$SHORT_SHA
        docker push getsentry/craft:$SHORT_SHA
        docker tag us.gcr.io/$PROJECT_ID/craft:$COMMIT_SHA getsentry/craft:$COMMIT_SHA
        docker push getsentry/craft:$COMMIT_SHA
        docker tag us.gcr.io/$PROJECT_ID/craft:$COMMIT_SHA getsentry/craft:latest
        docker push getsentry/craft:latest
timeout: 960s
secrets:
  - kmsKeyName: projects/sentryio/locations/global/keyRings/service-credentials/cryptoKeys/cloudbuild
    secretEnv:
      # This is a personal access token for the sentrybuilder account, encrypted using the
      # short guide at http://bit.ly/2Pg6uw9
      DOCKER_PASSWORD: |
        CiQAE8gN7y3OMxn+a1kofmK4Bi8jQZtdRFj2lYYwaZHVeIIBUzMSTQA9tvn8XCv2vqj6u8CHoeSP
        TVW9pLvSCorKoeNtOp0eb+6V1yNJW/+JC07DNO1KLbTbodbuza6jKJHU5xeAJ4kGQI78UY5Vu1Gp
        QcMK
