import {
  BaseArtifactProvider,
  RemoteArtifact,
  ArtifactProviderConfig,
} from '../artifact_providers/base';
import { CraftGCSClient, getGCSCredsFromEnv } from '../utils/gcsApi';
import { ConfigurationError } from '../utils/errors';

// TODO (kmclb) this type should be generated by the schema validator; once it
// is, can move to using it as the type for config passed to constructor
/** Necessary config for GCS artifact provider */
export interface GCSArtifactProviderConfig extends ArtifactProviderConfig {
  /** Bucket name */
  bucket: string;
}

/**
 * Google Cloud Storage artifact provider
 */
export class GCSArtifactProvider extends BaseArtifactProvider {
  /** Client for interacting with the GCS bucket */
  private readonly gcsClient: CraftGCSClient;

  public constructor(config: ArtifactProviderConfig) {
    super(config);
    const creds = getGCSCredsFromEnv(
      {
        name: 'CRAFT_GCS_STORE_CREDS_JSON',
      },
      {
        name: 'CRAFT_GCS_STORE_CREDS_PATH',
      }
    );

    // TODO (kmclb) get rid of this check once config validation is working
    if (!config.bucket) {
      throw new ConfigurationError(
        'No GCS bucket provided in artifact provider config!'
      );
    }

    this.gcsClient = new CraftGCSClient({
      bucketName: config.bucket,
      credentials: creds?.credentials,
      projectId: creds?.project_id,
    });
  }

  /**
   * @inheritDoc
   */
  protected async doDownloadArtifact(
    artifact: RemoteArtifact,
    downloadDirectory: string
  ): Promise<string> {
    return this.gcsClient.downloadArtifact(
      artifact.storedFile.downloadFilepath,
      downloadDirectory
    );
  }

  /**
   * @inheritDoc
   */
  protected async doListArtifactsForRevision(
    revision: string
  ): Promise<RemoteArtifact[]> {
    const { repoName, repoOwner } = this.config;
    return this.gcsClient.listArtifactsForRevision(
      repoOwner,
      repoName,
      revision
    );
  }
}

// TODO (kmclb) add support for a directory structure on the artifact provider
// (make desired path into filename when uploading to provider?)
