/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Craft project-specific configuration
 */
export interface CraftProjectConfig {
  github?: GitHubGlobalConfig;
  targets?: TargetConfig[];
  preReleaseCommand?: string;
  postReleaseCommand?: string;
  releaseBranchPrefix?: string;
  latestTargetBranch?: string;
  changelog?: string;
  changelogPolicy?: ChangelogPolicy;
  minVersion?: string;
  requireNames?: string[];
  statusProvider?: BaseStatusProvider;
  artifactProvider?: BaseArtifactProvider;
}
/**
 * Global (non-target!) GitHub configuration for the project
 */
export interface GitHubGlobalConfig {
  owner: string;
  repo: string;
  projectPath?: string;
}
/**
 * Generic target configuration
 */
export interface TargetConfig {
  name: string;
  id?: string;
  includeNames?: string;
  excludeNames?: string;
  [k: string]: any;
}
/**
 * Which service should be used for status checks
 */
export interface BaseStatusProvider {
  name: StatusProviderName;
  config?: {
    [k: string]: any;
  };
}
/**
 * Which service should be used for artifact storage
 */
export interface BaseArtifactProvider {
  name: ArtifactProviderName;
  config?: {
    [k: string]: any;
  };
}

/**
 * Different policies for changelog management
 */
export const enum ChangelogPolicy {
  Auto = 'auto',
  Simple = 'simple',
  None = 'none',
}
/**
 * Name of the status provider
 */
export const enum StatusProviderName {
  GitHub = 'github',
}
/**
 * Name of the artifact provider
 */
export const enum ArtifactProviderName {
  GCS = 'gcs',
  GitHub = 'github',
  None = 'none',
}
